name: hChat
version: '${version}'

main: dev.hauch.hchat.HChat
api-version: '1.18'
load: STARTUP

authors: [ Hauchdev ]
website: https://github.com/hauchdev/hChat

depend:
  - PlaceholderAPI
  - LuckPerms

softdepend:
  - Vault
  - DiscordSRV

permissions:
  hchat.*:
    description: Give access to all hchat commands
    default: op
    children:
      - hchat.message
      - hchat.reply
      - hchat.broadcast
      - hchat.reload
      - hchat.update
      - hchat.help
      - hchat.clear
      - hchat.ignore
      - hchat.sc
      - hchat.spy
      - hchat.spy.all
      - hchat.broadcast.color
      - hchat.lang
      - hchat.monitor.filter
      - hchat.bypass-log
      - hchat.channel

  hchat.message:
    description: Allows /message command
    default: true
  hchat.reply:
    description: Allows /reply command
    default: true
  hchat.reload:
    description: Allows /hchat reload command
    default: op
  hchat.update:
    description: Allows /hchat update command and update notifications
    default: op
  hchat.help:
    description: Allows /hchat help command
    default: true
  hchat.clear:
    description: Allows /clear command
    default: op
  hchat.ignore:
    description: Allows /ignore command
    default: true
  hchat.spy:
    description: Allows /spy command
    default: op
  hchat.spy.all:
    description: Receive all messages from all channels regardless of settings
    default: op
  hchat.broadcast:
    default: op
  hchat.broadcast.color:
    default: op
  hchat.lang:
    default: true
  hchat.monitor.filter:
    default: op
  hchat.bypass-log:
    default: op
  hchat.channel:
    description: Allows /channel command
    default: true

commands:
  message:
    description: Send a message to a player.
    aliases: [msg, tell, w, m, whisper]
    usage: /message <player> <message>
    permission: hchat.message
    permission-message: You do not have <permission> to use this command!
  reply:
    description: Reply to a player.
    aliases: [r]
    usage: /reply <message>
    permission: hchat.reply
    permission-message: You do not have <permission> to use this command!
  hchat:
    description: Main plugin command for hchat.
    usage: /hchat <reload|help>
    permission: hchat.help
    permission-message: You do not have <permission> to use this command!
  clear:
    description: Clear chat.
    usage: /clear
    permission: hchat.clear
    permission-message: You do not have <permission> to use this command!
  ignore:
    description: Ignore a player.
    usage: /ignore <player>
    permission: hchat.ignore
    permission-message: You do not have <permission> to use this command!
  spy:
    description: Spy on a player.
    usage: /spy
    permission: hchat.spy
    permission-message: You do not have <permission> to use this command!
  broadcast:
    description: Broadcast a message.
    usage: /broadcast
    aliases:
      - bc
    permission: hchat.broadcast
    permission-message: You do not have <permission> to use this command!
  channel:
    description: Switch chat channels.
    usage: /channel [name]
    aliases:
      - ch
    permission: hchat.channel
    permission-message: You do not have <permission> to use this command!